package com.neilturner.aerialviews.providers.youtube

import android.content.SharedPreferences
import androidx.core.content.edit
import java.util.Calendar
import java.util.ArrayDeque
import kotlin.random.Random
import timber.log.Timber

object QueryFormulaEngine {
    private const val TAG = "YouTubeQueries"
    private const val QUERY_CURSOR_PREFIX = "yt_query_cursor_"

    enum class QueryCategory {
        AERIAL,
        NATURE,
    }

    enum class ContentCategory(
        val key: String,
        val queryCategory: QueryCategory,
    ) {
        NATURE("nature", QueryCategory.NATURE),
        ANIMALS("animals", QueryCategory.NATURE),
        DRONE("drone", QueryCategory.AERIAL),
        CITIES("cities", QueryCategory.NATURE),
        SPACE("space", QueryCategory.NATURE),
        OCEAN("ocean", QueryCategory.NATURE),
        WEATHER("weather", QueryCategory.NATURE),
        WINTER("winter", QueryCategory.NATURE),
    }

    data class CategoryPreferences(
        val categoryNature: Boolean = true,
        val categoryAnimals: Boolean = true,
        val categoryDrone: Boolean = true,
        val categoryCities: Boolean = true,
        val categorySpace: Boolean = true,
        val categoryOcean: Boolean = true,
        val categoryWeather: Boolean = true,
        val categoryWinter: Boolean = true,
    ) {
        fun isEnabled(category: ContentCategory): Boolean =
            when (category) {
                ContentCategory.NATURE -> categoryNature
                ContentCategory.ANIMALS -> categoryAnimals
                ContentCategory.DRONE -> categoryDrone
                ContentCategory.CITIES -> categoryCities
                ContentCategory.SPACE -> categorySpace
                ContentCategory.OCEAN -> categoryOcean
                ContentCategory.WEATHER -> categoryWeather
                ContentCategory.WINTER -> categoryWinter
            }
    }

    data class CategoryQuery(
        val category: ContentCategory,
        val query: String,
    )

    // Native YouTube Search Parameters (Base64 Protobuf)
    const val SP_VIDEO_4K = "EgQQAXAB"                  // Video + 4K
    const val SP_VIDEO_4K_MEDIUM = "EgYQARgDcAE="         // Video + 4K + 4-20m Duration (Legacy)
    const val SP_VIDEO_4K_MEDIUM_MODERN = "EgYQARgFcAE="  // Video + 4K + 3-20m Duration (Modern)
    const val SP_VIDEO_4K_LONG = "EgYQARgCcAE="           // Video + 4K + >20m Duration
    const val SP_VIDEO_4K_RECENT = "EgYIBRABcAE="         // Video + 4K + Uploaded This Year
    const val SP_VIDEO_4K_VIEW_COUNT = "CAMSBBABcAE="     // Video + 4K + View Count Sort

    // Core Negative Search Clusters (Strict unhyphenated single tokens, deduplicated)
    val GLOBAL_NEGATIVE_TERMS = listOf(
        "-vlog", "-review", "-walk", "-walking", "-talking",
        "-guide", "-tour", "-hotel", "-resort", "-itinerary",
        "-tips", "-podcast", "-reaction", "-sora", "-ai", "-cgi", "-render", "-demo",
        "-beauty", "-hours"
    )

    val GEAR_WASTE_NEGATIVE_TERMS = listOf(
        "-test", "-tutorial", "-lut", "-luts", "-settings",
        "-bts", "-setup", "-vs", "-unboxing", "-commercial", "-oled"
    )

    private data class CategoryConfig(
        val queryCategory: QueryCategory,
        val queries: List<String>,
        val titleKeywords: Set<String>,
        val preferredTitleKeywords: Set<String> = emptySet(),
        val uploaderKeywords: Set<String> = emptySet(),
        val defaultSp: String = SP_VIDEO_4K_MEDIUM,
    )

    fun getSpForCategory(category: ContentCategory): String =
        categoryConfigs[category]?.defaultSp ?: SP_VIDEO_4K_MEDIUM

    /**
     * Anchored combinatorial queries: subject x anchor x constraint, prefixed
     * with 4k. Subject cycles fastest so consecutive ring draws differ in
     * subject, maximizing spread across refreshes. Every component is bounded
     * ambient vocabulary, so combinations cannot drift off-topic.
     */
    private fun buildMatrixQueries(
        subjects: List<String>,
        anchors: List<String>,
        constraints: List<String>,
        negativeTerms: List<String> = GLOBAL_NEGATIVE_TERMS,
    ): List<String> {
        if (subjects.isEmpty() || anchors.isEmpty() || constraints.isEmpty()) {
            return emptyList()
        }
        val negativeSuffix = if (negativeTerms.isNotEmpty()) " ${negativeTerms.distinct().joinToString(" ")}" else ""
        val total = subjects.size * anchors.size * constraints.size
        return List(total) { index ->
            val subject = subjects[index % subjects.size]
            val anchor = anchors[(index / subjects.size) % anchors.size]
            val constraint = constraints[(index / (subjects.size * anchors.size)) % constraints.size]
            "4k $subject $anchor $constraint$negativeSuffix"
        }
    }

    val aiVideoBlacklist =
        listOf(
            "ai generated",
            "made with ai",
            "generated by ai",
            "created with ai",
            "rendered by ai",
            "sora",
            "runway ml",
            "stable diffusion",
            "midjourney video",
            "pika labs",
            "kling ai",
            "ai nature",
            "ai cinematic",
            "ai animation",
            "ai short film",
            "artificial intelligence video",
            "synthetically generated",
            "ai art video",
            "neural network video",
            "rendered with ai",
            "cgi",
            "cg animation",
            "3d animation",
            "3d render",
            "rendered",
            "procedural",
            "unreal engine",
            "blender render",
            "virtual scenery",
            "fantasy landscape",
            "dreamscape",
        )

    val bumperTitleBlacklist =
        listOf(
            "subscribe",
            "click here",
            "watch more",
            "full video",
            "part 1",
            "part 2",
            "episode",
            "compilation",
            "best of",
            "top 10",
            "reaction",
            "review",
            "unboxing",
            "vlog",
            "travel vlog",
            "travel diary",
            "travel guide",
            "travel film",
            "travel movie",
            "travel cinematic",
            "talking",
            "hosted by",
            "presented by",
            "tour guide",
            "city tour",
            "hotel",
            "resort",
            "things to do",
            "itinerary",
            "road trip",
            "backpacking",
            "backpacker",
            "honeymoon",
            "vacation",
            "vacay",
            "tutorial",
            "how to",
            "cooking",
            "gaming",
            "challenge",
            "prank",
            "storytime",
            "day in my life",
            "grwm",
            "get ready with me",
            "haul",
            "mukbang",
            "wallpaper",
            "background video",
            "animated",
            "animation",
            "cgi",
            "3d",
            "render",
            "rendered",
            "loop",
        )

    val qualitySignals =
        listOf(
            "no music",
            "no talking",
            "slow motion",
            "8k",
            "4k hdr",
            "cinematic",
            "timelapse",
            "real footage",
            "documentary",
            "nature film",
            "wildlife",
        )

    private val categoryConfigs =
        linkedMapOf(
            ContentCategory.NATURE to
                CategoryConfig(
                    queryCategory = QueryCategory.NATURE,
                    defaultSp = SP_VIDEO_4K_MEDIUM,
                    queries =
                        buildMatrixQueries(
                            subjects =
                                listOf(
                                    "forest landscape",
                                    "mountain valley",
                                    "river gorge",
                                    "waterfall",
                                    "alpine meadow",
                                    "canyon plateau",
                                    "desert sand dunes",
                                    "arid sandstone oasis"
                                ),
                            anchors =
                                listOf(
                                    "Hoh Rain Forest",
                                    "Jiuzhaigou",
                                    "Yakushima",
                                    "Val di Funes",
                                    "Vatnajökull",
                                    "Torres del Paine",
                                    "Olympic Peninsula",
                                    "Monteverde",
                                    "Athabasca",
                                    "Plitvice",
                                    "Sossusvlei Namib",
                                    "Atacama Valle de la Luna",
                                    "Lençóis Maranhenses"
                                ),
                            constraints =
                                listOf(
                                    "real footage no talking",
                                    "ambient sound 4k",
                                    "documentary 4k",
                                    "cinematic landscape"
                                ),
                            negativeTerms = GLOBAL_NEGATIVE_TERMS + listOf("-safari", "-tour", "-atv", "-dune bashing"),
                        ),
                    titleKeywords =
                        setOf(
                            "forest",
                            "mountain",
                            "landscape",
                            "river",
                            "waterfall",
                            "valley",
                            "canyon",
                            "meadow",
                            "countryside",
                            "national park",
                            "trail",
                            "alpine",
                            "desert",
                            "dunes",
                            "sand dunes",
                        ),
                    preferredTitleKeywords =
                        setOf(
                            "real footage",
                            "documentary",
                            "nature film",
                            "national park",
                            "desert",
                            "dunes",
                        ),
                ),
            ContentCategory.ANIMALS to
                CategoryConfig(
                    queryCategory = QueryCategory.NATURE,
                    defaultSp = SP_VIDEO_4K_MEDIUM,
                    queries =
                        buildMatrixQueries(
                            subjects =
                                listOf(
                                    "safari wildlife",
                                    "birds documentary",
                                    "marine life",
                                    "arctic animals",
                                    "forest wildlife",
                                    "savanna wildlife"
                                ),
                            anchors =
                                listOf(
                                    "Serengeti",
                                    "Masai Mara",
                                    "Okavango Delta",
                                    "Svalbard",
                                    "Galapagos",
                                    "Pantanal"
                                ),
                            constraints =
                                listOf(
                                    "real footage no talking",
                                    "documentary 4k",
                                    "cinematic wildlife",
                                    "natural sound 4k"
                                ),
                            negativeTerms = GLOBAL_NEGATIVE_TERMS + listOf("-zoo", "-pet", "-hunting", "-hunter", "-cartoon"),
                        ),
                    titleKeywords =
                        setOf(
                            "wildlife",
                            "animal",
                            "animals",
                            "safari",
                            "bird",
                            "birds",
                            "whale",
                            "elephant",
                            "deer",
                            "lion",
                            "tiger",
                            "penguin",
                            "dolphin",
                            "marine life",
                        ),
                    preferredTitleKeywords =
                        setOf(
                            "documentary",
                            "national geographic",
                            "nat geo",
                            "real footage",
                        ),
                    uploaderKeywords = setOf("nat geo", "national geographic", "bbc earth", "discovery"),
                ),
            ContentCategory.DRONE to
                CategoryConfig(
                    queryCategory = QueryCategory.AERIAL,
                    defaultSp = SP_VIDEO_4K_MEDIUM,
                    queries =
                        buildMatrixQueries(
                            subjects =
                                listOf(
                                    "drone landscape",
                                    "aerial coastline",
                                    "bird's eye view",
                                    "drone fjord",
                                    "mountain flyover",
                                    "cinematic aerial",
                                    "DJI Inspire 3 aerial",
                                    "Mavic 3 Cine ProRes",
                                    "desert dune flyover",
                                    "sandstone canyon aerial"
                                ),
                            anchors =
                                listOf(
                                    "Geirangerfjord",
                                    "Lofoten",
                                    "Landmannalaugar",
                                    "Lauterbrunnen",
                                    "Dolomites",
                                    "Na Pali Coast",
                                    "Raja Ampat",
                                    "Senja",
                                    "Madeira",
                                    "Milford Sound",
                                    "Rub al Khali dunes",
                                    "Namib-Naukluft aerial"
                                ),
                            constraints =
                                listOf(
                                    "cinematic 4k",
                                    "slow flyover",
                                    "real footage",
                                    "4k no music"
                                ),
                            negativeTerms = GLOBAL_NEGATIVE_TERMS + GEAR_WASTE_NEGATIVE_TERMS,
                        ),
                    titleKeywords =
                        setOf(
                            "drone",
                            "aerial",
                            "flyover",
                            "flythrough",
                            "fpv",
                            "bird's eye",
                            "uav",
                            "cinematic aerial",
                            "dune flyover",
                            "desert aerial",
                        ),
                    preferredTitleKeywords =
                        setOf(
                            "drone",
                            "aerial",
                            "fpv",
                            "bird's eye",
                            "real footage",
                        ),
                ),
            ContentCategory.OCEAN to
                CategoryConfig(
                    queryCategory = QueryCategory.NATURE,
                    defaultSp = SP_VIDEO_4K_MEDIUM,
                    queries =
                        buildMatrixQueries(
                            subjects =
                                listOf(
                                    "ocean waves",
                                    "coral reef underwater",
                                    "sea cliffs coastline",
                                    "beach waves sunset",
                                    "deep sea ocean",
                                    "kelp forest"
                                ),
                            anchors =
                                listOf(
                                    "Raja Ampat",
                                    "Bora Bora",
                                    "Maldives",
                                    "Great Barrier Reef",
                                    "Fernando de Noronha",
                                    "Seychelles",
                                    "Whitsundays",
                                    "Bonaire"
                                ),
                            constraints =
                                listOf(
                                    "real footage no music",
                                    "ambient 4k",
                                    "documentary 4k",
                                    "relaxing real footage"
                                ),
                            negativeTerms = GLOBAL_NEGATIVE_TERMS + listOf("-surfing", "-surfer", "-shark", "-cruise", "-party"),
                        ),
                    titleKeywords =
                        setOf(
                            "ocean",
                            "sea",
                            "underwater",
                            "beach",
                            "waves",
                            "reef",
                            "coral",
                            "coast",
                            "coastal",
                            "marine",
                            "sea cliffs",
                        ),
                    preferredTitleKeywords =
                        setOf(
                            "underwater",
                            "coral reef",
                            "marine life",
                            "real footage",
                            "documentary",
                        ),
                ),
            ContentCategory.SPACE to
                CategoryConfig(
                    queryCategory = QueryCategory.NATURE,
                    defaultSp = SP_VIDEO_4K_LONG,
                    queries =
                        buildMatrixQueries(
                            subjects =
                                listOf(
                                    "earth from space",
                                    "iss earth view",
                                    "milky way night sky",
                                    "aurora borealis",
                                    "deep space nebula",
                                    "bioluminescent night ocean"
                                ),
                            anchors =
                                listOf(
                                    "international space station",
                                    "hubble james webb",
                                    "Atacama dark sky",
                                    "Aoraki Mackenzie dark sky"
                                ),
                            constraints =
                                listOf(
                                    "ambient sound no music",
                                    "real footage 4k",
                                    "cinematic 4k"
                                ),
                            negativeTerms = GLOBAL_NEGATIVE_TERMS + listOf("-ufo", "-alien", "-conspiracy", "-scifi", "-animation"),
                        ),
                    titleKeywords =
                        setOf(
                            "space",
                            "earth from space",
                            "iss",
                            "nasa",
                            "aurora",
                            "northern lights",
                            "milky way",
                            "night sky",
                            "stars",
                            "moonrise",
                            "space station",
                            "dark sky",
                            "astrophotography",
                            "bioluminescence",
                        ),
                    preferredTitleKeywords =
                        setOf(
                            "nasa",
                            "iss",
                            "earth from space",
                            "milky way",
                            "aurora",
                            "northern lights",
                            "dark sky",
                            "astrophotography",
                        ),
                    uploaderKeywords = setOf("nasa", "esa"),
                ),
            ContentCategory.CITIES to
                CategoryConfig(
                    queryCategory = QueryCategory.NATURE,
                    defaultSp = SP_VIDEO_4K_MEDIUM,
                    queries =
                        buildMatrixQueries(
                            subjects =
                                listOf(
                                    "city skyline",
                                    "downtown cityscape",
                                    "urban architecture",
                                    "city lights night",
                                    "waterfront skyline",
                                    "rooftop sunset"
                                ),
                            anchors =
                                listOf(
                                    "tokyo",
                                    "new york",
                                    "singapore",
                                    "chicago",
                                    "hong kong",
                                    "dubai",
                                    "london",
                                    "paris",
                                    "seattle",
                                    "sydney",
                                    "san francisco",
                                    "shanghai"
                                ),
                            constraints =
                                listOf(
                                    "real footage",
                                    "cinematic 4k"
                                ),
                            negativeTerms = GLOBAL_NEGATIVE_TERMS + listOf("-food", "-streetfood", "-shopping", "-traffic"),
                        ),
                    titleKeywords =
                        setOf(
                            "city",
                            "urban",
                            "skyline",
                            "downtown",
                            "architecture",
                            "cityscape",
                            "metropolis",
                            "streets",
                            "street",
                            "rooftop",
                            "city lights",
                        ),
                    preferredTitleKeywords =
                        setOf(
                            "city skyline",
                            "urban",
                            "downtown",
                            "architecture",
                            "city lights",
                            "cityscape",
                        ),
                ),
            ContentCategory.WEATHER to
                CategoryConfig(
                    queryCategory = QueryCategory.NATURE,
                    defaultSp = SP_VIDEO_4K_LONG,
                    queries =
                        buildMatrixQueries(
                            subjects =
                                listOf(
                                    "thunderstorm lightning",
                                    "storm clouds",
                                    "fog rolling valley",
                                    "heavy rain landscape",
                                    "dramatic storm front"
                                ),
                            anchors =
                                listOf(
                                    "over mountains",
                                    "over ocean",
                                    "over plains",
                                    "desert sunrise"
                                ),
                            constraints =
                                listOf(
                                    "real footage no music",
                                    "ambient sound",
                                    "nature documentary",
                                    "calm rain natural sound"
                                ),
                            negativeTerms = GLOBAL_NEGATIVE_TERMS + listOf("-damage", "-disaster", "-tornado", "-destruction", "-loop"),
                        ),
                    titleKeywords =
                        setOf(
                            "storm",
                            "thunderstorm",
                            "lightning",
                            "rain",
                            "cloud",
                            "clouds",
                            "fog",
                            "mist",
                            "storm front",
                            "weather",
                        ),
                    preferredTitleKeywords =
                        setOf(
                            "thunderstorm",
                            "lightning",
                            "storm clouds",
                            "real footage",
                        ),
                ),
            ContentCategory.WINTER to
                CategoryConfig(
                    queryCategory = QueryCategory.NATURE,
                    defaultSp = SP_VIDEO_4K_MEDIUM,
                    queries =
                        buildMatrixQueries(
                            subjects =
                                listOf(
                                    "winter forest snow",
                                    "frozen lake ice",
                                    "snowfall landscape",
                                    "glacier icebergs",
                                    "snowy mountain valley",
                                    "arctic frozen tundra"
                                ),
                            anchors =
                                listOf(
                                    "Arctic",
                                    "Alps",
                                    "Norway",
                                    "Iceland",
                                    "Lofoten",
                                    "Lapland"
                                ),
                            constraints =
                                listOf(
                                    "4k no music",
                                    "real footage",
                                    "documentary 4k",
                                    "peaceful snowfall"
                                ),
                            negativeTerms = GLOBAL_NEGATIVE_TERMS + listOf("-ski", "-snowboard", "-resort", "-cabin", "-chalet"),
                        ),
                    titleKeywords =
                        setOf(
                            "winter",
                            "snow",
                            "snowfall",
                            "arctic",
                            "frozen",
                            "ice",
                            "glacier",
                            "polar",
                            "snowy",
                        ),
                    preferredTitleKeywords =
                        setOf(
                            "winter",
                            "arctic",
                            "glacier",
                            "polar",
                            "real footage",
                        ),
                ),
        )

    fun generateQueryPool(count: Int = 25): List<String> =
        generateQueryPool(
            count = count,
            prefs = CategoryPreferences(),
            entropySeed = refreshSeed(),
        )

    fun generateQueryPool(
        baseQuery: String,
        count: Int = 25,
        entropySeed: Long = 0L,
        prefs: CategoryPreferences = CategoryPreferences(),
    ): List<String> {
        val categoryPool = generateQueryPool(count = count, prefs = prefs, entropySeed = entropySeed)
        val normalizedBaseQuery = baseQuery.trim()
        if (normalizedBaseQuery.isBlank()) {
            return categoryPool
        }

        return (
            listOf(normalizedBaseQuery) +
                categoryPool +
                listOf("$normalizedBaseQuery 4k", "$normalizedBaseQuery cinematic")
        ).distinct()
            .map(::sanitizeQueryForAmbientPlayback)
            .distinct()
            .shuffled(Random(entropySeed xor dailySeed() xor refreshSeed()))
            .take(count)
    }

    fun generateQueryPool(
        count: Int,
        prefs: CategoryPreferences,
        entropySeed: Long = 0L,
    ): List<String> {        val enabledPools =
            categoryConfigs
                .filterKeys(prefs::isEnabled)
                .ifEmpty { defaultPools() }

        val selectedQueries =
            roundRobinQueries(
                pools = enabledPools.mapValues { (category, queries) ->
                    queries.queries
                        .shuffled(seedForCategory(category, entropySeed))
                        .toCollection(ArrayDeque())
                },
                count = count,
            )

        val expandedQueries = expandQueriesForNarrowCategorySelection(selectedQueries, count)
        val finalPool =
            expandedQueries
                .ifEmpty { SAFE_FALLBACK_QUERIES.take(count) }
                .map(::sanitizeQueryForAmbientPlayback)
                .distinct()
                .take(count)
        Timber.tag(TAG).d("Generated %s YouTube search variants across %s categories", finalPool.size, enabledPools.size)
        return finalPool
    }

    /**
     * Main-pool query selection with persistent per-category ring cursors.
     * Random shuffles re-dealt overlapping hands every refresh (small pools,
     * ~3 draws each: ~46% per-category collision); sequential ring slices
     * guarantee zero query repetition until a category's pool wraps. Cursors
     * survive process death and category toggles (modulo pool size).
     * Fallback/delta pools keep random selection — only the main pool needs
     * the strict guarantee.
     */
    fun generateRingQueryPool(
        count: Int,
        prefs: CategoryPreferences,
        sharedPreferences: SharedPreferences,
    ): List<String> {
        val enabledPools =
            categoryConfigs
                .filterKeys(prefs::isEnabled)
                .ifEmpty { defaultPools() }

        val selected = mutableListOf<String>()
        val cursors =
            enabledPools.mapValues { (category, config) ->
                readQueryCursor(sharedPreferences, category.key, config.queries.size)
            }.toMutableMap()

        while (selected.size < count) {
            var advanced = false
            for (category in ContentCategory.entries) {
                val config = enabledPools[category] ?: continue
                if (selected.size >= count || config.queries.isEmpty()) {
                    continue
                }
                val cursor = cursors.getValue(category) % config.queries.size
                selected += config.queries[cursor]
                cursors[category] = (cursor + 1) % config.queries.size
                advanced = true
            }
            if (!advanced) {
                break
            }
        }

        cursors.forEach { (category, cursor) ->
            writeQueryCursor(sharedPreferences, category.key, cursor)
        }

        val expandedQueries = expandQueriesForNarrowCategorySelection(selected.distinct(), count)
        val finalPool =
            expandedQueries
                .ifEmpty { SAFE_FALLBACK_QUERIES.take(count) }
                .map(::sanitizeQueryForAmbientPlayback)
                .distinct()
                .take(count)
        Timber.tag(TAG).d("Generated %s ring YouTube search variants across %s categories", finalPool.size, enabledPools.size)
        return finalPool
    }

    private fun queryCursorKey(categoryKey: String): String = "$QUERY_CURSOR_PREFIX$categoryKey"

    private fun readQueryCursor(
        sharedPreferences: SharedPreferences,
        categoryKey: String,
        poolSize: Int,
    ): Int {
        if (poolSize <= 0) {
            return 0
        }
        val stored = sharedPreferences.getInt(queryCursorKey(categoryKey), 0)
        return ((stored % poolSize) + poolSize) % poolSize
    }

    private fun writeQueryCursor(
        sharedPreferences: SharedPreferences,
        categoryKey: String,
        cursor: Int,
    ) {
        sharedPreferences.edit { putInt(queryCursorKey(categoryKey), cursor) }
    }

    fun generateFallbackQueryPool(
        baseQuery: String,
        count: Int = 12,
        entropySeed: Long = 0L,
        prefs: CategoryPreferences = CategoryPreferences(),
    ): List<String> {
        val enabledQueries =
            generateQueryPool(
                count = (count * 3).coerceAtLeast(18),
                prefs = prefs,
                entropySeed = entropySeed xor 0x51A8C27L,
            )

        val fallbackQueries =
            if (enabledQueries.isNotEmpty()) {
                enabledQueries
            } else {
                buildSafeFallbackQueries(baseQuery)
            }

        return fallbackQueries
            .distinct()
            .shuffled(Random(entropySeed xor weeklySeed() xor refreshSeed()))
            .take(count)
    }

    fun categoryOf(query: String): QueryCategory =
        categoryForQuery(query)?.queryCategory
            ?: if (AERIAL_QUERY_REGEX.containsMatchIn(query)) {
                QueryCategory.AERIAL
            } else {
                QueryCategory.NATURE
            }

    private fun stripNegativeTerms(query: String): String =
        query.split(" ").filterNot { it.startsWith("-") }.joinToString(" ").trim()

    private val queryToCategoryExactMap: Map<String, ContentCategory> by lazy {
        val map = HashMap<String, ContentCategory>(4096)
        categoryConfigs.forEach { (category, config) ->
            config.queries.forEach { configuredQuery ->
                val normConfig = configuredQuery.lowercase()
                val sanitConfig = sanitizeQueryForAmbientPlayback(configuredQuery).lowercase()
                val strippedConfig = stripNegativeTerms(normConfig)
                val strippedSanitConfig = stripNegativeTerms(sanitConfig)

                map.putIfAbsent(normConfig, category)
                map.putIfAbsent(sanitConfig, category)
                map.putIfAbsent(strippedConfig, category)
                map.putIfAbsent(strippedSanitConfig, category)
            }
        }
        map
    }

    private val queryPrefixesByCategory: List<Pair<String, ContentCategory>> by lazy {
        val prefixes = ArrayList<Pair<String, ContentCategory>>(4096)
        categoryConfigs.forEach { (category, config) ->
            config.queries.forEach { configuredQuery ->
                val normConfig = configuredQuery.lowercase()
                val sanitConfig = sanitizeQueryForAmbientPlayback(configuredQuery).lowercase()
                val strippedConfig = stripNegativeTerms(normConfig)
                val strippedSanitConfig = stripNegativeTerms(sanitConfig)

                prefixes.add("$normConfig " to category)
                if (sanitConfig != normConfig) {
                    prefixes.add("$sanitConfig " to category)
                }
                if (strippedConfig != normConfig && strippedConfig != sanitConfig) {
                    prefixes.add("$strippedConfig " to category)
                }
                if (strippedSanitConfig != strippedConfig && strippedSanitConfig != sanitConfig && strippedSanitConfig != normConfig) {
                    prefixes.add("$strippedSanitConfig " to category)
                }
            }
        }
        prefixes.distinctBy { it.first }.sortedByDescending { it.first.length }
    }

    fun categoryForQuery(query: String): ContentCategory? {
        val normalizedQuery = query.trim().lowercase()
        if (normalizedQuery.isBlank()) {
            return null
        }

        val strippedQuery = stripNegativeTerms(normalizedQuery)

        // 1. O(1) fast path: exact match against precomputed raw, sanitized, and stripped configured queries
        queryToCategoryExactMap[normalizedQuery]?.let { return it }
        queryToCategoryExactMap[strippedQuery]?.let { return it }

        // 2. Fast prefix match for queries with appended variation tokens
        queryPrefixesByCategory.firstOrNull { (prefix, _) ->
            normalizedQuery.startsWith(prefix) || strippedQuery.startsWith(prefix)
        }?.second?.let { return it }

        val inferredByKeywords =
            categoryConfigs.entries
                .map { (category, config) ->
                    val titleMatches = config.titleKeywords.count { keyword -> normalizedQuery.contains(keyword.lowercase()) }
                    val preferredMatches = config.preferredTitleKeywords.count { keyword -> normalizedQuery.contains(keyword.lowercase()) }
                    val uploaderMatches = config.uploaderKeywords.count { keyword -> normalizedQuery.contains(keyword.lowercase()) }
                    category to (titleMatches + preferredMatches * 2 + uploaderMatches * 2)
                }.maxByOrNull { (_, score) -> score }
                ?.takeIf { (_, score) -> score > 0 }
                ?.first

        return inferredByKeywords
    }

    fun enabledCategories(prefs: CategoryPreferences): List<ContentCategory> =
        ContentCategory.entries.filter(prefs::isEnabled).ifEmpty { defaultPools().keys.toList() }

    fun matchesCandidateCategory(
        title: String,
        uploader: String,
        category: ContentCategory?,
    ): Boolean {
        if (category == null) {
            return true
        }

        val config = categoryConfigs.getValue(category)
        val titleLower = title.lowercase()
        val uploaderLower = uploader.lowercase()

        val directMatch = config.titleKeywords.any(titleLower::contains)
        val uploaderMatch =
            config.uploaderKeywords.isNotEmpty() &&
                config.uploaderKeywords.any(uploaderLower::contains)
        val strongTitleMatch = config.preferredTitleKeywords.any(titleLower::contains)
        return directMatch || strongTitleMatch || uploaderMatch
    }

    fun categoryMatchScore(
        title: String,
        uploader: String,
        category: ContentCategory?,
    ): Int {
        if (category == null) {
            return 0
        }

        val config = categoryConfigs.getValue(category)
        val titleLower = title.lowercase()
        val uploaderLower = uploader.lowercase()
        val titleMatches = config.titleKeywords.count(titleLower::contains)
        val preferredMatches = config.preferredTitleKeywords.count(titleLower::contains)
        val uploaderMatches = config.uploaderKeywords.count(uploaderLower::contains)

        return titleMatches + preferredMatches * 2 + uploaderMatches * 2
    }

    fun totalPossibleCombinations(): Long =
        categoryConfigs.values.sumOf { config -> config.queries.size.toLong() }

    fun freshnessSeed(baseQuery: String): String =
        "${baseQuery.trim()}|${weeklySeed()}|${dailySeed()}|${refreshSeed()}|${timeBucket()}"

    fun categorySignature(prefs: CategoryPreferences): String =
        ContentCategory.entries.joinToString(separator = ",") { category ->
            if (prefs.isEnabled(category)) category.key else "-${category.key}"
        }

    internal fun sanitizeQueryForAmbientPlaybackForTest(query: String): String =
        sanitizeQueryForAmbientPlayback(query)

    private fun sanitizeQueryForAmbientPlayback(query: String): String {
        var sanitized = query.trim()
        if (sanitized.isBlank()) {
            return sanitized
        }

        QUERY_TERM_REPLACEMENTS.forEach { (pattern, replacement) ->
            sanitized = sanitized.replace(pattern, replacement)
        }

        return sanitized.replace("\\s+".toRegex(), " ").trim()
    }

    private fun defaultPools(): Map<ContentCategory, CategoryConfig> =
        linkedMapOf(
            ContentCategory.NATURE to categoryConfigs.getValue(ContentCategory.NATURE),
            ContentCategory.OCEAN to categoryConfigs.getValue(ContentCategory.OCEAN),
            ContentCategory.DRONE to categoryConfigs.getValue(ContentCategory.DRONE),
        )

    private fun roundRobinQueries(
        pools: Map<ContentCategory, ArrayDeque<String>>,
        count: Int,
    ): List<String> {
        val selected = mutableListOf<String>()
        val buckets = pools.toMutableMap()

        while (selected.size < count && buckets.isNotEmpty()) {
            val exhausted = mutableListOf<ContentCategory>()

            ContentCategory.entries.forEach { category ->
                val bucket = buckets[category] ?: return@forEach
                val query = bucket.pollFirst()
                if (query != null) {
                    selected += query
                }
                if (bucket.isEmpty()) {
                    exhausted += category
                }
                if (selected.size >= count) {
                    return@forEach
                }
            }

            exhausted.forEach(buckets::remove)
        }

        return selected.distinct().take(count)
    }

    private fun expandQueriesForNarrowCategorySelection(
        baseQueries: List<String>,
        count: Int,
    ): List<String> {
        if (baseQueries.isEmpty()) {
            return emptyList()
        }
        if (baseQueries.size >= count) {
            return baseQueries.take(count)
        }

        val expandedQueries = LinkedHashSet(baseQueries)

        QUERY_VARIATION_SUFFIXES.forEach { suffix ->
            baseQueries.forEach { query ->
                val suffixToken = suffix.trim()
                if (query.contains(suffixToken, ignoreCase = true)) {
                    return@forEach
                }

                val firstNegativeIndex = query.indexOf(" -")
                val expanded = if (firstNegativeIndex != -1) {
                    val positivePart = query.substring(0, firstNegativeIndex).trim()
                    val negativePart = query.substring(firstNegativeIndex).trim()
                    "$positivePart $suffixToken $negativePart"
                } else {
                    "$query $suffixToken"
                }

                expandedQueries += expanded
                if (expandedQueries.size >= count) {
                    return expandedQueries.take(count)
                }
            }
        }

        return expandedQueries.take(count)
    }

    private fun seedForCategory(
        category: ContentCategory,
        entropySeed: Long,
    ): Random =
        when (category) {
            ContentCategory.DRONE -> Random(refreshSeed() xor entropySeed xor category.ordinal.toLong())
            else -> Random(dailySeed() xor entropySeed xor category.ordinal.toLong())
        }

    private fun weeklySeed(): Long {
        val calendar = Calendar.getInstance()
        return calendar.get(Calendar.YEAR).toLong() * 1000 + calendar.get(Calendar.WEEK_OF_YEAR)
    }

    private fun dailySeed(): Long {
        val calendar = Calendar.getInstance()
        return calendar.get(Calendar.YEAR).toLong() * 10_000L + calendar.get(Calendar.DAY_OF_YEAR)
    }

    private fun refreshSeed(): Long = System.currentTimeMillis() / (1000L * 60L * 60L * 6L)

    private fun timeBucket(): String =
        when (Calendar.getInstance().get(Calendar.HOUR_OF_DAY)) {
            in 5..9 -> "morning"
            in 10..16 -> "day"
            in 17..20 -> "evening"
            else -> "night"
        }

    private val SAFE_FALLBACK_QUERIES =
        listOf(
            "4k national park landscape documentary",
            "4k ocean waves real footage no music",
            "4k drone aerial landscape no music",
        )
    private val QUERY_VARIATION_SUFFIXES =
        listOf(
            "real footage",
            "no talking",
            "no music",
            "ambient",
            "cinematic",
            "documentary",
        )
    private val QUERY_TERM_REPLACEMENTS =
        listOf(
            Regex("\\btimelapse\\b", RegexOption.IGNORE_CASE) to "real footage",
            Regex("\\btime\\s+lapse\\b", RegexOption.IGNORE_CASE) to "real footage",
            Regex("\\bhyperlapse\\b", RegexOption.IGNORE_CASE) to "real footage",
            Regex("\\bfpv\\b", RegexOption.IGNORE_CASE) to "cinematic aerial",
            Regex("\\bflythrough\\b", RegexOption.IGNORE_CASE) to "slow flyover",
            Regex("\\bdrone racing\\b", RegexOption.IGNORE_CASE) to "drone landscape",
            Regex("\\bfast motion\\b", RegexOption.IGNORE_CASE) to "real footage",
        )

    private fun buildSafeFallbackQueries(baseQuery: String): List<String> {
        val normalizedBaseQuery = baseQuery.trim()
        if (normalizedBaseQuery.isBlank()) {
            return SAFE_FALLBACK_QUERIES
        }

        return (
            listOf(
                normalizedBaseQuery,
                "$normalizedBaseQuery documentary 4k",
                "$normalizedBaseQuery no talking 4k",
            ) + SAFE_FALLBACK_QUERIES
        ).map(::sanitizeQueryForAmbientPlayback)
            .distinct()
    }

    private val AERIAL_QUERY_REGEX =
        Regex(
            "(aerial|drone|flyover|flythrough|fpv|bird's eye)",
            RegexOption.IGNORE_CASE,
        )
}
